### ISSUE TITLE
No HDMI Output

### ISSUE THREAD

**Issue by montamal** [JackHack96/dell-xps-9570-ubuntu-respin#83] opened 2019-03-18 00:30 UTC
_Not sure if this has to do with this project, but I'm looking for help_
Hi, 
I've got my XPS 15 9570 this week, the FHD one with the i7-8750H processor and GTX 1050Ti Mobile. I'm using the latest BIOS version (1.8.1), AHCI mode and Secure Boot OFF.

Booted into Windows at first, and my HDMI output was working with the multiple monitors I tried.
Proceeded to install Ubuntu using the respun ISO (not dual-booting), everything went smoothly, tried 'nvidia-smi' afterwards, drivers were okay.

Then went on to try an external monitor using the HDMI out and got a "No signal". I can see the external display with xrandr, Nvidia Server and the Settings Display tab, but still no signal on any of my monitors. 

**Couple things that stood out to me:** 
xrandr is naming the output DP1-3 and the resolutions are sometimes right (1080p, 2K) and sometimes off (lower 4:3) on the same monitor model.

**Haven't tried:**  

- Using the USB-C port.

- An HDMI to _X_ adapter.

**Tried:**

- Switching to the intel profile.

- All Nvidia drivers from 390 to 418.

- Multiple monitors using different resolutions and HDMI cables.

- Reinstalling using the official Ubuntu 18.04 ISO and running the post-install script.

All to no avail.

Can someone help me out on this? Am I missing something? Seems like I'm the only one around experiencing this issue.

Should I downgrade the BIOS to an earlier version? 

Any tips or possible solutions will be greatly appreciated 👍 
Thanks !

**Comment by JackHack96** [comment] 2019-03-18 17:27
Did you also tried booting up with HDMI attached?
BTW I never experienced this issue with the XPS (but with my older laptop instead)

**Comment by montamal** [comment] 2019-03-18 19:17
@JackHack96 Thanks for the fast reply !

Yes I tried booting with the HDMI already plugged in, still no signal.

I downgraded my BIOS version to 1.5.0 (Oct. 2018) after finding a guide that referenced this version and this script being used successfully, still no luck. Also tried forcing video output through every port using xrandr.

here's my xrandr output with a 1080p Asus monitor attached pre-boot, after a fresh install using the respun ISO and the nvidia profile:
`
alex@alex-XPS-15-9570:~$ xrandr
Screen 0: minimum 8 x 8, current 2944 x 1080, maximum 32767 x 32767
eDP-1-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1920x1080     60.00*+  59.97    59.96    59.93  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864      60.00  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1-1 disconnected (normal left inverted right x axis y axis)
DP-1-2 disconnected (normal left inverted right x axis y axis)
DP-1-3 connected 1024x768+1920+0 (normal left inverted right x axis y axis) 531mm x 299mm
   1024x768      60.00* 
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08 
`

![Screenshot from 2019-03-18 15-14-39](https://user-images.githubusercontent.com/24536404/54557069-b908f100-4990-11e9-8c2f-3242cffed5a3.png)

**Comment by JackHack96** [comment] 2019-03-18 19:35
This is so odd...
I just tried with my laptop and it works flawlessly (note that I have DP-3 too)
![image_2019-03-18_20-33-55](https://user-images.githubusercontent.com/3611330/54558149-44987700-49bd-11e9-9d07-9eeb3a39bb40.png)

Have you also tried manually forcing the output on DP-3 using xrandr?

**Comment by montamal** [comment] 2019-03-18 21:01
@JackHack96  Notice mine actually says DP-1-3, I'll look into that. And yes I tried forcing the output.

I'd really like if you could answer these couple questions:
Are you currently using nvidia 418 too?
What kernel version are you on? (uname -r)
BIOS version? (if you don't mind looking into it)
Did you use the tweak script yourself? If so, was it the first commit ?

I'm hoping to be able to reproduce good results if my setup is exactly the same as someone that succeeded.

Thanks alot for your help!

**Comment by JackHack96** [comment] 2019-03-18 21:05
> @JackHack96 Notice mine actually says DP-1-3, I'll look into that. And yes I tried forcing the output.
> 
> I'd really like if you could answer these couple questions:
> Are you currently using nvidia 418 too?
> What kernel version are you on? (uname -r)
> BIOS version? (if you don't mind looking into it)
> Did you use the tweak script yourself? If so, was it the first commit ?
> 
> I'm hoping to be able to reproduce good results if my setup is exactly the same as someone that succeeded.
> 
> Thanks alot for your help!

- Yes, I'm using nvidia 418.43 drivers (but for testing HDMI output I used Intel)
- I'm using Xanmod kernel version 4.20 (because 5.0 is causing blinking blank screen and I still can't figure out why)
- Using latest 1.8.1 BIOS
- I didn't use the script, as my machine was the one where I tested various configuration for getting Ubuntu 18.04 to work properly, and all the editing was done manually (and from that edits I made the script and the respin)

**Comment by montamal** [comment] 2019-03-18 21:08
@JackHack96 Thanks for letting me know, I'll have another go at it!

**Comment by montamal** [comment] 2019-03-19 13:30
I did it all over using the kernel you listed and 1.8.1 BIOS and was still not able to use the HDMI out. 
I left it out before thinking it wasn't important, but it might be: 
On boot, I'm getting ACPI Errors (AE_ALREADY_EXISTS) and a little bit of coil whining before the login screen appears.

**The good news:**
Got my hands on a USB-C to HDMI adapter and it worked right away with all my monitors.

Guess I'll live in dongle town for a while 💯 

Thanks again for helping out, I might leave this issue open just in case anyone experiences the same issue.

**Comment by JackHack96** [comment] 2019-03-20 07:37
I too have those ACPI errors and a bit of coil whine during boot up, it's a pretty common error, though it doesn't compromise the experience.

Happy to see the dongle is working, at least you've found a workaround...
I'm sorry I can't help further, I really don't know what to do at this point

**Comment by Codeklopper** [comment] 2019-04-03 06:50
Looking for a solution as well. Think it is not related to this respin, since i'm experiencing similar issues with Linux Mint (on my XPS-9570). A USB-C to HDMI adapter indeed works. What also makes the HDMI output work is reducing the resolution to 2560x1440 (higher resolutions don't work). I have no issues using the HDMI when using Windows.

**Comment by montamal** [comment] 2019-04-03 13:51
> ...What also makes the HDMI output work is reducing the resolution to 2560x1440 (higher resolutions don't work).

I have the 1080p version and could not get the HDMI out working on any resolution, there may be small differences between the two models.

**Comment by JackHack96** [comment] 2019-05-02 16:27
I get a better experience on 19.04 with external monitors. Closing this issue (ask me to re-open it if you want)

**Closed by JackHack96** 2019-05-02 16:27 UTC
Labels: help wanted

**Comment by elichai** [comment] 2019-07-12 23:12
Hi, I have the exact same problem on the XPS 15 7590.
Through HDMI, xrandr shows the external display but it's pitch black.
Through type C it works fine.

Did anyone ever figured this out?

**Comment by JackHack96** [comment] 2019-07-14 08:49
I had some problems at my university, but very randomly and only with some projectors.
I still never understood the cause though

**Comment by urwithajit9** [comment] 2019-07-25 18:36
Hi All,

I am also facing same issue and not being able solve after trying the various means. The strange thing is one it started working and then again next day same issue. No change in hardware, software etc.

Not able to connect my laptop running ubuntu 16.4 to any projector. 
uname -r 
4.15.0-55-generic

xrandr -q
Screen 0: minimum 320 x 200, current 1366 x 768, maximum 8192 x 8192
eDP-1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1366x768      60.00*+  40.00  
   1360x768      59.80    59.96  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  

any help would be very helpful

**Comment by alexandroskon** [comment] 2019-09-24 09:58
Playing with different resolutions and rates using `xrandr` solved the problem for me. If I go with a resolution of 1920x1080 and a rate of 60 Hz the TV shows a black screen. Changing to other modes and rates solves the problem. For example, typing in a terminal 

> `xrandr --output DP-1-3 --mode 1360x768 --rate 60`

made it work. If I go for a resolution of 1920x1080, I have output only for a rate of 25 Hz. I don't know why exactly this happens. Maybe it depends on the TV.

Hope this helps!
