### ISSUE TITLE
sudo prime-select nvidia does to work

### ISSUE THREAD

**Issue by bifunctor** [JackHack96/dell-xps-9570-ubuntu-respin#79] opened 2019-03-10 14:52 UTC
Hi all 
I tried to switch from intel to nvidia as the following" 

```
sudo prime-select nvidia
[sudo] password for developer: 
sudo: prime-select: command not found
```

What am I doing wrong? 

Thanks

**Comment by erenatas** [comment] 2019-03-10 21:28
I believe I had this when I installed from resprung iso. Open your terminal and type
```
bash -c "$(curl -fsSL https://raw.githubusercontent.com/JackHack96/dell-xps-9570-ubuntu-respin/master/xps-tweaks.sh)"
```
And install the missing. If any error happens, pleasepost them here.

**Comment by JackHack96** [comment] 2019-03-11 13:20
@bifunctor Yes this is usually caused by missing or failing nvidia drivers installation. Try what @erenatas suggested

**Comment by erenatas** [comment] 2019-03-13 08:47
@JackHack96 I think you should close it.

**Closed** 2019-03-13 08:48 UTC

**Comment by LynuxSydney** [comment] 2022-02-22 04:04
I tried @erenatas command but 
it says 
This script is made for Ubuntu 18.04/20.04!

**Comment by JackHack96** [comment] 2022-02-22 06:36
The script is indeed just for 18.04/20.04. Non-LTS variants are not supported while for the upcoming 22.04 I'll check if tweaks are still needed (I believe not).
